steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/callpilot-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/callpilot-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'callpilot-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/callpilot-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'callpilot-backend-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-secrets'
      - 'ELEVENLABS_API_KEY=elevenlabs-api-key:latest,GOOGLE_CALENDAR_API_KEY=google-calendar-api-key:latest,GOOGLE_PLACES_API_KEY=google-places-api-key:latest,GOOGLE_MAPS_API_KEY=google-maps-api-key:latest,TWILIO_ACCOUNT_SID=twilio-account-sid:latest,TWILIO_AUTH_TOKEN=twilio-auth-token:latest,TWILIO_PHONE_NUMBER=twilio-phone-number:latest,SECRET_KEY=jwt-secret-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/callpilot-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
